version: "3.8"

services:
  neo4j:
    image: neo4j:5.25.1-community
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"    # HTTP (Neo4j Browser)
      - "7687:7687"    # Bolt (driver dùng)
    environment:
      NEO4J_AUTH: neo4j/kguser2005          # user/pass đăng nhập
      NEO4J_server_memory_pagecache_size: 512M
      NEO4J_server_memory_heap_initial__size: 512M
      NEO4J_server_memory_heap_max__size: 1G
    
      # Bật APOC (với image mới thường đã có sẵn APOC core)
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
      - neo4j_import:/var/lib/neo4j/import

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  neo4j_import:
